// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9pZIxK8BK4-HqPqMUTGjbMx2hMBtc78M',
    appId: '1:360679595267:web:a5a0dd68cbd07efcba9d36',
    messagingSenderId: '360679595267',
    projectId: 'foodpanda-7ecb8',
    authDomain: 'foodpanda-7ecb8.firebaseapp.com',
    storageBucket: 'foodpanda-7ecb8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVvoUDdeQlX2N9W_R7IOAZWPZvha1CTv4',
    appId: '1:360679595267:android:58029c4a049442c3ba9d36',
    messagingSenderId: '360679595267',
    projectId: 'foodpanda-7ecb8',
    storageBucket: 'foodpanda-7ecb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYngytanAwYsEbv9Rcb43yavJyI4vFrck',
    appId: '1:360679595267:ios:f62d5f14f79b3507ba9d36',
    messagingSenderId: '360679595267',
    projectId: 'foodpanda-7ecb8',
    storageBucket: 'foodpanda-7ecb8.appspot.com',
    iosClientId: '360679595267-jvksr2n7v55seu8cgttmbs3mo63cjnsu.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodpandaUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYngytanAwYsEbv9Rcb43yavJyI4vFrck',
    appId: '1:360679595267:ios:8f6a79df2e971533ba9d36',
    messagingSenderId: '360679595267',
    projectId: 'foodpanda-7ecb8',
    storageBucket: 'foodpanda-7ecb8.appspot.com',
    iosClientId: '360679595267-4ijdm1ee7a4th07ce7o9angcknd7qam0.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodpandaUser.RunnerTests',
  );
}
